### ISSUE TITLE
Define treatment of null values in data sets

### ISSUE THREAD

**Issue by wbailey** [sbyrnes/logistical.js#15]
I have been play around with sylvester and come across some interesting behavior regarding nulls and vectors.  This led me to consider the absence of data in our data sets and how they are treated.  For example, consider the following

```
> var Cat = require('sylvester');
undefined
> v1 = Cat.Vector.create([1,2,3])
[1, 2, 3]
> v2 = Cat.Vector.create([4,5,6])
[4, 5, 6]
> v1.dot(v2)
32
```

Now let's replace this calculation with the following:

```
> v2 = Cat.Vector.create([null,null,6])
[, , 6]
> v1.dot(v2)
18
```

It is treating null to be the equivalent of 0.   The same thing for matrices:

```
> m1 = Cat.Matrix.create([[1,2],[3,4]]);
[1, 2]
[3, 4]
> m2 = Cat.Matrix.create([[5,6],[7,8]]);
[5, 6]
[7, 8]
> m1.multiply(m2)
[19, 22]
[43, 50]
```

Inserting some nulls produces:

```
> m2 = Cat.Matrix.create([[null,6],[null,8]]);
[, 6]
[, 8]
> m1.multiply(m2)
[0, 22]
[0, 50]
```

Now imagine a data set where nulls are present.  It makes me think we have a couple of options:

1. Require data sets to not allow nulls and raise an error
1. Allow nulls, treat them as zeroes and document accordingly

What is the standard?

**Comment by sbyrnes** [comment]
For our purposes, I think that treating null values as zero should be fine. The entries in each component vector of the matrix are really just features, and having a zero value means that feature will not be considered (there is no coefficient that would change the value so its as if it is static). 

Unless there is some way that a zero value will result in a non-fixed value for all inputs in which case we should replace it with a value that does map to a fixed value.

**Comment by wbailey** [comment]
I can't think of a way for the last statement to be true.
