### ISSUE TITLE
Select Matrix/Math Package

### ISSUE THREAD

**Issue by wbailey** [sbyrnes/logistical.js#4]
We need to pick a package to use that allows the creation and efficient manipulation of matrices.  At a minimum we need the following operations:
* Creation from file
* dot product
* transpose

**Comment by sbyrnes** [comment]
I don't know if there are any others beyond Sylvester: https://www.npmjs.com/package/sylvester

Which is still more than exist for Go. =)

**Comment by wbailey** [comment]
Selected sylvester
